services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/qrcodedb
      DB_USERNAME: qrcodeuser
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8181:8181"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: http://backend:8181/api
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:3000"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qrcodedb
      POSTGRES_USER: qrcodeuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U qrcodeuser -d qrcodedb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
